<a href="https://colab.research.google.com/github/NestorRodriguez/MisionTIC-2022-Ciclo1/blob/main/Librerias_numpy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np 

matrizCeros = np.zeros((2,3))
print(matrizCeros)

# matriz cuadrada de 1
matrizUnos = np.ones((4,4))
print(matrizUnos)

matrizVacia = np.empty((3,2))
print(matrizVacia)

matriz = np.random.rand(3,2)
print(matriz)

matrizInt = np.random.randint(50 , 100, size=(2, 3))
print(matrizInt)

matriz = np.full((2,2) , 5)
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.52140519 0.62851833]
 [0.53343239 0.57018143]
 [0.17959886 0.17380963]]
[[67 57 67]
 [72 79 68]]
[[5 5]
 [5 5]]


In [28]:
# Vectores con tamaños constantes
matrizEspaciado = np.arange(5, 30, 5)
print(matrizEspaciado)
matrizEspaciado = np.arange(0, 2, 0.5)
print(matrizEspaciado)

start = 1
while start < 5:
  matrizEspaciado = np.arange(5, 30, start)
  print(matrizEspaciado)
  start += 1
print('Pasos de cinco')
start = 5
while start < 40:
  matrizEspaciado = np.arange(5, 30, start)
  print(matrizEspaciado)
  start += 5


[ 5 10 15 20 25]
[0.  0.5 1.  1.5]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]
[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  8 11 14 17 20 23 26 29]
[ 5  9 13 17 21 25 29]
Pasos de cinco
[ 5 10 15 20 25]
[ 5 15 25]
[ 5 20]
[ 5 25]
[5]
[5]
[5]


In [30]:

matrizIdentidad = np.identity(4)
print(matrizIdentidad)
matrizIdentidad = np.eye(4,4)
print(matrizIdentidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
matriz = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(matriz)
print(matriz.ndim)
print(matriz.dtype)
print(matriz.size)
print(matriz.shape)
matriz = matriz.reshape(3,4)
print(matriz)
vector = matriz.reshape(12)
print(vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
int64
12
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Solicitar al usuario las dimensiones de la matriz, crearla y el usuario debe digitar solo los 
# valores diagonales de la matriz , los demás valores de la matriz deben ser un valor mayor a 0.