<a href="https://colab.research.google.com/github/NestorRodriguez/MisionTIC-2022-Ciclo1/blob/main/Librerias_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import sys
import time

# Por qué numpy
# Tamaño

s = range(1000000)
print(sys.getsizeof(s)*len(s))

d = np.arange(1000000)
print(d.size * d.itemsize)

# Tiempo
SIZE = 2000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

print('Listas')
start = time.time()
# Convertir en iterador con zip y luego separarlos en un vector
iterador = zip(l1,l2)
result = [(x,y) for x,y in iterador]
print((time.time()-start)*1000)
print("Numpy")
start = time.time()
d = a1 + a2
print((time.time()-start)*1000)

48000000
8000000
Listas
400.64072608947754
Numpy
4.706859588623047


In [32]:
# Ejercicios con numpy
# Vectores
vectorUnos = np.ones((8))
print(vectorUnos)

vectorCeros = np.zeros((4))
print(vectorCeros)

vectorVacio = np.empty((2))
print(vectorVacio)

vector = np.append(2,4)
print(vector)

vector2 = np.append(vector, [10, 20, 30])
print(vector2)

vector3 = np.array([2,4])
print(vector3)

vectorAleatorio = np.random.rand(3)
print(vectorAleatorio)

vectorAleatorio1 = np.random.randint(5,20,size=5)
print(vectorAleatorio1)

vectorConValorUnico = np.full((8), 100)
print(vectorConValorUnico)


[1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0.]
[1.e-323 2.e-323]
[2 4]
[ 2  4 10 20 30]
[2 4]
[0.86410328 0.52181957 0.41529611]
[ 5 13  5 12 19]
[100 100 100 100 100 100 100 100]
