<a href="https://colab.research.google.com/github/NestorRodriguez/MisionTIC-2022-Ciclo1/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
# Matrices - operaciones aritméticas
import numpy as np

matriz = np.array([(1,2,3),(4,5,6)])
print(matriz)
print(matriz.max())
print(matriz.min())
print(matriz.sum())
print(matriz.sum(0))
print(matriz.prod())
# La matriz debe ser de igual tamaño, es decir, en este caso es de 2x3
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
# El vector debe ser del mismo tamaño de las columnas
a = np.array([(1,2,3),(4,5,6)])
c = np.array([(2,2,2)])
print(c)
print(a + c)
print(a - c)
print(a * c)
print(a / c)

[[1 2 3]
 [4 5 6]]
6
1
21
[5 7 9]
720
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]]
[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [49]:
# Ejercicios 
#Cambiar la posición de textos de un arreglo
# Nike es mejor que Adidas
# Adidas es mejor que Nike
texto ='Por ahora, Nike es mejor que Adidas'
print(texto)
palabras = texto.split()
print(palabras)
for i in range(len(palabras)):
  if 'Nike' in palabras[i]:
    palabras[i] = 'Adidas'
  elif 'Adidas' in palabras[i]:
    palabras[i] = 'Nike'

print(*palabras)

Por ahora, Nike es mejor que Adidas
['Por', 'ahora,', 'Nike', 'es', 'mejor', 'que', 'Adidas']
Por ahora, Adidas es mejor que Nike
